import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between items-center bg-purple-700 px-2 py-2">
          <div className="home"><Link href="/">Home</Link></div>
        <div className="flex  gap-5  ">
          <Link href="/log-in" >LogIn</Link>
          <Link href="/sign-up">SignUp</Link>
        </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
